[workspace]
members = [
    "atlas_lib",
    "atlas_gen",
    "atlas_sim",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
debug = false
opt-level = 3
debug-assertions = false
overflow-checks = false
