[general]
name = "Default Genfile"
version = "0.1.0"
base_version = "0.1.0"
description = "This is the default Genfile used for world generation."

[[tiles]]
name = "plain"
color = [0.60, 0.93, 0.44]

[[tiles]]
name = "forest"
color = [0.19, 0.51, 0.21]

[[tiles]]
name = "water"
color = [0.36, 0.71, 0.86]

[[tiles]]
name = "deep water"
color = [0.18, 0.37, 0.63]

[[tiles]]
name = "low mountain"
color = [0.7, 0.7, 0.7]

[[tiles]]
name = "high mountain"
color = [0.4, 0.4, 0.4]

# Transform modes:
# * mode.Fill.Simple          Set every tile
#     * value.Tile or vale.Height
# * mode.Fill.Conditional     Set tile based on condition
#     * value.Tile or value.Height
#     * min - minimum height condition
#     * max - maximum height condition
# * mode.Fill.Flood           Set random region based on condition
#     * value.Tile or value.Height
#     * origins = number of region origins to pick
#     * min - minimum height condition
#     * max - maximum height condition
# * mode.Noise.Pepper         Set tile based on random chance
#     * value.Tile or value.Height
#     * frequency - chance of occurence
#     * deviation - random +- deviation value (applicable to height)
#     * on.Tile (optional) - apply only to tiles of this type
# * mode.Noise.Perlin         Set tile based on Perlin noise map
#     * value.Height - noise amplitude
#     * offset - offset added to random value
#     * scale - Perlin noise scale, higher means more detail

[[transforms]]
name = "superflat"
mode.Fill.Simple = { value.Tile = "plain" }

[[transforms]]
name = "height map"
mode.Noise.Perlin = { value.Height = 5.0, offset = 0.0, scale = 2.5 }

[[transforms]]
name = "random height deviation"
mode.Noise.Pepper = { value.Height = 0.0, frequency = 1.0, deviation = 0.5 }

[[transforms]]
name = "random forest"
mode.Noise.Pepper = { value.Tile = "forest", frequency = 0.2, deviation = 0.0, on.Tile = "plain" }

[[transforms]]
name = "flood oceans"
mode.Fill.Flood = { value.Tile = "water", origins = 10, min = -9999.9, max = 0.0 }

[[transforms]]
name = "set deep water"
mode.Fill.Conditional = { value.Tile = "deep water", min = -9999.9, max = -2.0 }

[[transforms]]
name = "set hills"
mode.Fill.Conditional = { value.Tile = "low mountain", min = 2.5, max = 9999.9 }

[[transforms]]
name = "set high hills"
mode.Fill.Conditional = { value.Tile = "high mountain", min = 3.5, max = 9999.9 }

#[[transforms]]
#name = "pepper"
#mode.Noise.Pepper = { value.Height = 2, frequency = 0.5 }
#tile = { default = "plain", datatype = "tile", values = [] }
#frequency = { default = 0.1, datatype = "f32", range = [0.0, 0.1] }
