[package]
name = "atlas_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
atlas_lib = { path = "../atlas_lib" }     # inhouse common library
noise = "0.8.2"                           # noise generation
